# Generated by Django 3.1.14 on 2022-03-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creared_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
